export class HUD {
  constructor(){this.elements={health:document.getElementById('health'),armor:document.getElementById('armor'),money:document.getElementById('money'),ammo:document.getElementById('ammo'),reserve:document.getElementById('reserve'),weapon:document.getElementById('weapon-name'),timer:document.getElementById('round-timer'),round:document.getElementById('round-label'),aScore:document.getElementById('attack-score'),dScore:document.getElementById('defend-score'),bomb:document.getElementById('bomb-indicator'),zone:document.getElementById('zone-indicator'),grenades:document.getElementById('grenades'),interaction:document.getElementById('interaction'),fps:document.getElementById('fps-counter')};this.radar=document.getElementById('radar');this.ctx=this.radar.getContext('2d');this.lastFps=0;}
  update(game,dt){const p=game.player,w=p.inventory.active;this.elements.health.textContent=Math.ceil(p.health);this.elements.armor.textContent=Math.ceil(p.armor);this.elements.money.textContent=`$${p.money}`;this.elements.weapon.textContent=w?.definition?.name||'—';this.elements.ammo.textContent=w?.ammo??'—';this.elements.reserve.textContent=w?.reserve??'—';this.elements.grenades.textContent=p.inventory.slots.grenades.map(()=> '●').join(' ')||'○ ○ ○';const t=game.modeId==='bomb'?game.rounds.time:game.mode?.time||0;this.elements.timer.textContent=`${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.ceil(t%60)).padStart(2,'0')}`;this.elements.round.textContent=game.modeId==='bomb'?`РАУНД ${game.rounds.number}`:'КОМАНДНЫЙ БОЙ';const scores=game.modeId==='bomb'?game.rounds.scores:game.mode.scores;this.elements.aScore.textContent=scores.attackers;this.elements.dScore.textContent=scores.defenders;this.elements.bomb.style.display=p.inventory.slots.bomb?'block':'none';this.elements.zone.style.display=game.bombMode?.nearSite(p.position)&&p.inventory.slots.bomb?'block':'none';this.drawRadar(game);if(game.settings.values.showFps){this.lastFps=this.lastFps*.9+(1/Math.max(dt,.001))*.1;this.elements.fps.textContent=`${Math.round(this.lastFps)} FPS`;}else this.elements.fps.textContent='';}
  drawRadar(game){const c=this.ctx;c.clearRect(0,0,190,190);c.save();c.translate(95,95);c.rotate(game.playerCamera.yaw);c.strokeStyle='#758b75';c.globalAlpha=.45;c.strokeRect(-75,-70,150,140);const scale=150/Math.max(game.mapConfig.size.width,game.mapConfig.size.depth);const draw=(x,z,color,r=3)=>{const dx=(x-game.player.position.x)*scale,dz=(z-game.player.position.z)*scale;if(Math.abs(dx)>86||Math.abs(dz)>86)return;c.fillStyle=color;c.beginPath();c.arc(dx,dz,r,0,Math.PI*2);c.fill();};for(const s of game.mapConfig.bombSites)draw(s.x,s.z,s.id==='A'?'#d86543':'#e1a34d',6);for(const bot of game.botManager.bots){if(!bot.alive)continue;if(bot.team===game.player.team||game.isSpotted(bot))draw(bot.position.x,bot.position.z,bot.team===game.player.team?'#83aebb':'#d9634f',3);}draw(game.player.position.x,game.player.position.z,'#d8ed70',4);if(game.bombMode?.bomb.visible)draw(game.bombMode.bomb.position.x,game.bombMode.bomb.position.z,'#fff36a',4);c.restore();}
  interaction(label,value){const root=this.elements.interaction;root.style.display=value>0?'block':'none';root.querySelector('span').textContent=label;root.querySelector('progress').value=Math.min(1,value);}
  message(text,type='info'){const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=text;document.getElementById('message-stack').append(el);setTimeout(()=>el.remove(),3100);}
  kill(killer,victim,weapon){const el=document.createElement('div');el.className='kill';el.innerHTML=`<span class="${killer.team==='attackers'?'a':'d'}">${killer.name}</span> · ${weapon} · <span class="${victim.team==='attackers'?'a':'d'}">${victim.name}</span>`;document.getElementById('killfeed').prepend(el);setTimeout(()=>el.remove(),4300);}
  damage(){const e=document.getElementById('damage-direction');e.style.opacity='1';setTimeout(()=>e.style.opacity='0',180);}
  hit(killed=false){const crosshair=document.getElementById('crosshair');crosshair.classList.remove('hit','kill-hit');void crosshair.offsetWidth;crosshair.classList.add(killed?'kill-hit':'hit');setTimeout(()=>crosshair.classList.remove('hit','kill-hit'),150);}
}
